

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(ID INT PRIMARY KEY, NOME VARCHAR(255));
INSERT INTO CLIENTE VALUES(1, 'João Ribeiro');
INSERT INTO CLIENTE VALUES(2, 'Heloisa Silva');
INSERT INTO CLIENTE VALUES(3, 'Antonio Mendes');
INSERT INTO CLIENTE VALUES(4, 'Maria Helena');


DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO(ID INT PRIMARY KEY, NOME VARCHAR(255), PRECO FLOAT(24));
INSERT INTO PRODUTO VALUES(1, 'Vibranium 1', 120.10);
INSERT INTO PRODUTO VALUES(2, 'Vibranium 2', 150.10);


DROP TABLE IF EXISTS PEDIDO;
CREATE TABLE PEDIDO(ID INT PRIMARY KEY, ID_CLIENTE INT, PROCESSADO BOOLEAN);
INSERT INTO PEDIDO VALUES(1, 2, FALSE);
INSERT INTO PEDIDO VALUES(2, 3, FALSE);
INSERT INTO PEDIDO VALUES(3, 1, FALSE);
INSERT INTO PEDIDO VALUES(4, 4, FALSE);


DROP TABLE IF EXISTS PEDIDO_PRODUTO;
CREATE TABLE PEDIDO_PRODUTO(ID_PEDIDO INT, ID_PRODUTO INT, QUANTIDADE INT, VALOR FLOAT(24));
INSERT INTO PEDIDO_PRODUTO VALUES(1, 1, 3, 360.30);
INSERT INTO PEDIDO_PRODUTO VALUES(1, 2, 2, 300.20);
INSERT INTO PEDIDO_PRODUTO VALUES(2, 2, 4, 600.40);




