<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receita">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string" />
                <xs:element name="ingredientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingrediente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="quantidade" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:decimal">
                                                        <xs:minInclusive value="0" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="unidade" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="xícaras" />
                                                        <xs:enumeration value="gramas" />
                                                        <xs:enumeration value="colheres" />
                                                        <xs:enumeration value="colheres de sopa" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="estado" type="xs:string" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="instrucoes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="passo" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="200" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nome" type="xs:string" />
            <xs:attribute name="tempo_de_preparo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9][0-9]:[0-9][0-9]:[0-9][0-9]" />
                        <xs:length value="8" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="tempo_de_cozimento">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9][0-9]:[0-9][0-9]:[0-9][0-9]" />
                        <xs:length value="8" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>